#!/bin/sh
set -e

export HOME=/tmp

mkdir -p /tmp/.openclaw
mkdir -p /tmp/workspace

echo "=== Running onboard wizard ==="

# Run onboard in non-interactive mode
node dist/index.js onboard \
  --non-interactive \
  --accept-risk \
  --mode local \
  --auth-choice apiKey \
  --gateway-port ${PORT:-8080} \
  --gateway-bind lan \
  --skip-skills \
  --skip-health || true

echo "=== Onboard complete ==="

# Extract the token that was generated by the wizard
CONFIG_FILE="$HOME/.openclaw/openclaw.json"
if [ -f "$CONFIG_FILE" ]; then
  GENERATED_TOKEN=$(node -e "
    const fs = require('fs');
    const config = JSON.parse(fs.readFileSync('$CONFIG_FILE', 'utf8'));
    const token = config.gateway?.auth?.token || 'NO_TOKEN_FOUND';
    console.log(token);
  ")
  echo "=============================================="
  echo "GENERATED TOKEN: $GENERATED_TOKEN"
  echo "=============================================="
  echo "ACCESS URL: https://openclaw-production-cf83.up.railway.app/?token=$GENERATED_TOKEN"
  echo "=============================================="
fi

echo "=== Config file contents ==="
cat "$CONFIG_FILE" 2>/dev/null || echo "No config file found"
echo "=== End config ==="

# Start the gateway (it will use the token from config)
exec node dist/index.js gateway --port ${PORT:-8080} --bind lan
